// let array=[1,2,3,4,5]
// console.log(array);
// console.log(array[3]);
// console.log(array.length)
// console.log(array[array.length-3])
// array.push(6)
// console.log(array)
// array.pop();
// console.log(array)
// array.shift();
// console.log(array)
// array.unshift("a")
// console.log(array)
// array.splice(1,2,"b","c")
// console.log(array)

// let arr= array.slice(1,3)
// console.log(arr)






// let student={
//     name:"Praveen",
//     rollno:123456,
//     dep:"ECE",
//     sec:"D"
// }
// console.log(student)
// console.log(student.name)
// console.log(student.dep)
// console.log(student["dep"])
// student.dep="EEE"
// student.age=22
// console.log(student)
   


let shopping={
    items:["shirt","pant","shoes"],
    price:[1000,2000,3000],
    discount:10,
    snacks:["chips","chocale"]
}
console.log(shopping)
console.log(shopping.items)
console.log(shopping.price)
console.log(shopping.discount)